POST http://localhost:5206/programs
Content-Type: application/json

{
    "name": "Back1",
    "description": "Strength/powerlifting back workout -  Wednesday",
    "w_date": "2024-03-02",
    "exercises": [
        "Deadlift 5x5",
        "Heavy barbell row 3x10",
        "Pulldown wide-grip 3x10",
        "Cable row 3x10"
    ]
}