POST http://localhost:5206/programs
Content-Type: application/json

{
    "name": "Legs",
    "description": "Killer leg workout!",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "exercises": [
        "Heavy squats 3x10",
        "Leg extensions 3x10",
        "Hamstring curls 3x10",
        "Calf raises 3x10",
        "Leg press machine 3x10"
    ]
}